version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: poseidon
      MYSQL_ROOT_PASSWORD: poseidon
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  wordpress:
    build: .
    container_name: wordpress
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: poseidon
      WORDPRESS_DB_NAME: wordpress

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"

  portracker:
    image: ghcr.io/porthole-ascend-cinnamon/portracker:latest
    container_name: portracker
    ports:
      - "7070:7070"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  db_data:
