name: Déploiement sous Nginx v4

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Copier les fichiers vers le serveur avec SCP
      - name: Copy files with SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./app1/*"
          target: "/var/www/app"

      # 3. Installer Nginx si besoin et configurer le site
      - name: Setup Nginx and restart service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if ! command -v nginx >/dev/null 2>&1; then
              sudo apt update -y
              sudo apt install -y nginx
            fi

            sudo mkdir -p /var/www/app
            sudo chown -R $USER:$USER /var/www/app

            if [ ! -f /etc/nginx/sites-available/app ]; then
              sudo bash -c 'cat > /etc/nginx/sites-available/app <<EOL
server {
    listen 80;
    server_name _;
    root /var/www/app;
    index index.html;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL'
              sudo ln -sf /etc/nginx/sites-available/app /etc/nginx/sites-enabled/app
            fi

            sudo nginx -t
            sudo systemctl reload nginx || sudo systemctl restart nginx
