name: Déploiement App1 - Nginx

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Génération d’un fichier version.txt
      - name: Générer un fichier version.txt
        run: |
          echo "Application: App1" > app1/version.txt
          echo "Date: $(date)" >> app1/version.txt
          echo "Commit: $GITHUB_SHA" >> app1/version.txt

      # 3. Copier uniquement le contenu de app1/ vers le serveur
      - name: Déployer les fichiers sur le serveur
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./app1/*"
          target: "/var/www/app"

      # 4. Configuration Nginx + reload
      - name: Configurer et recharger Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if ! command -v nginx >/dev/null 2>&1; then
              sudo apt update -y
              sudo apt install -y nginx
            fi
            sudo mkdir -p /var/www/app
            sudo chown -R $USER:$USER /var/www/app

            # Configuration Nginx si non existante
            if [ ! -f /etc/nginx/sites-available/app ]; then
              sudo tee /etc/nginx/sites-available/app > /dev/null <<EOF
              server {
                  listen 80;
                  server_name _;
                  root /var/www/app;
                  index index.html;
                  location / {
                      try_files \$uri \$uri/ =404;
                  }
              }
EOF
              sudo ln -sf /etc/nginx/sites-available/app /etc/nginx/sites-enabled/app
            fi

            sudo nginx -t
            sudo systemctl reload nginx || sudo systemctl restart nginx

      # 5. Vérification post-déploiement
      - name: Vérifier que le site répond
        run: |
          curl -I http://${{ secrets.SSH_HOST }} || exit 1
